//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCourse
    {
        public long Id { get; set; }
        public long StudentId { get; set; }
        public long CourseId { get; set; }
        public string Year { get; set; }
        public long GradeId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Grade Grade { get; set; }
        public virtual Student Student { get; set; }
    }
}
